### ISSUE TITLE
Pass args to grlc Dockerfile

### ISSUE THREAD

**Issue by arnikz** [candYgene/docker-images#1]
For example, the `sparql_endpoint` value is currently hard-coded in `config.ini`. One could use `ARG` to pass the value to `Dockerfile`.

**Comment by c-martinez** [comment]
True -- but this does not matter too much as the `sparql_endpoint` in `config.ini` is the value set by default. But all our queries can take the endpoint as a parameter.

**Comment by arnikz** [comment]
fixed in `clariah/grlc:latest` (https://github.com/candYgene/docker-images/pull/8)
