### ISSUE TITLE
grlc is listening to a different port than expected

### ISSUE THREAD

**Issue by arnikz** [candYgene/docker-images#4]
sometimes http://localhost:32768/api/local works instead of http://localhost:8088/api/local (port `8088` set in `docker-compose.yml`)

**Comment by c-martinez** [comment]
Strange -- I guess you figured out the correct by running `docker ps -a` ? and I imagine you had a port mapping such as `8888:32768` or so?

**Comment by arnikz** [comment]
Ah, I used another `docker-compose.yml` which had incorrect `port` config (fixed https://github.com/candYgene/pbg-ld/commit/49f0c87330d3a7c08b4f19c074156f120a0c663b).
