### ISSUE TITLE
grlc endpoints do not work anymore

### ISSUE THREAD

**Issue by arnikz** [candYgene/docker-images#5]
My local [API](http://localhost:8088/api/local) shows up but requests on the endpoints do not return anything  after changing the default SPARQL endpoint `http://virtuoso:8890/sparql`(?) to `http://localhost:8890/sparql`. It seems that the commit https://github.com/candYgene/docker-images/commit/1e593b416e533f82137ffa0c608bd95cf5c654b3 broke it.

**Comment by c-martinez** [comment]
`docker ps -a`? `docker network inspect`?

**Comment by arnikz** [comment]
As mentioned, grlc is running and is accessible via web (this time on the correct port #4 )

```
$ docker ps -a
2c9a6b78ce84        docker-images_virtuoso      "/bin/sh -c ./run.sh"    2 hours ago         Up 40 seconds                    1111/tcp, 0.0.0.0:8890->8890/tcp   docker-images_virtuoso_1_42414b658e64
e8170a87161e        docker-images_grlc          "/bin/sh -c 'gunicor…"   2 hours ago         Up 43 seconds                    0.0.0.0:8088->8088/tcp             docker-images_grlc_1_96f9fac390e9
2f35f64e2c4f        docker-images_notebook      "/bin/sh -c 'jupyter…"   2 hours ago         Up 41 seconds                    0.0.0.0:8888->8888/tcp             docker-images_notebook_1_cc5647087356
```
```
$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "7709a6779d3da8488a19dd501b1af6f618e7022dd3097e41c81e1bc163c1a96c",
        "Created": "2018-11-28T21:31:13.414826084+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

**Comment by c-martinez** [comment]
Is there any useful output on the console?

**Comment by c-martinez** [comment]
```$ docker-compose --version
docker-compose version 1.23.1, build b02f130
```

`http://localhost:8088/` gives me the grlc landing page

`http://localhost:8088/api/local` gives me the api with the candygene queries

Ah! but when executing the query `countFeatures` I get `TypeError: Failed to fetch`

Actually, if I go to `http://localhost:8890/sparql` I get nothing.

**Comment by c-martinez** [comment]
Update: you were right: I've changes `config.ini` so that servername is `localhost`, otherwise the SwaggerUI does not like it -- it looks like cross-site scripting: SwaggerUI is loaded from `localhost:8088/api/local`, but calling a data from `grlc:8088` (which is where config.ini tells it data is loaded from).

So when you put it on the hpc-cloud, you might want to change config.ini to match

**Comment by c-martinez** [comment]
However, I think if you just call the grlc endpoint from the notebook, it would not be an issue at all (it is not cross-site scripting when you load data in python via `requests`).
